version: '3.8'

services:
  # Notre serveur Express
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - PORT=5000
    networks:
      - ppe-network

  # Notre application React (Vite)
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true # Nécessaire pour que Vite ne s'arrête pas tout seul
    networks:
      - ppe-network

networks:
  ppe-network:
    driver: bridge